---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker-gcp

inputs:
- name: create-infrastructure-output
  path: tfstate
- name: gcp-concourse
- name: tfstate-version

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: gcp-concourse/tasks/wipe-env.sh
