---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker-gcp

inputs:
- name: gcp-concourse
- name: pivnet-opsmgr

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: gcp-concourse/tasks/upload-opsman.sh
